Create a 1D array of numbers from 0 to 9.

In [1]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 3×3 numpy array of all True’s

In [2]:
arrT = np.ones((3,3),dtype =bool)
arrT

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Given an array as input, print only odd numbers as output

In [3]:
#Method 1:
arr = np.array([1,2,3,4,5,6])
lis = arr.tolist()
only_odd = [num for num in lis if num % 2 == 1] 
  
print(only_odd) 

[1, 3, 5]


In [4]:
#Method2:
arr = np.array([1,2,3,4,5,6])
for a in arr.tolist():
     if a % 2 != 0: 
            print(a, end = " ") 
    

1 3 5 

Replace all odd numbers in arr with -2

In [5]:
arr = np.array([1,2,3,4,5,6])
lis = arr.tolist()
only_odd = [num for num in lis if num % 2 == 1] 
for n,a in enumerate(lis):
    if a % 2 == 1:
        lis[n] = 2
print("odd numbers are :",only_odd)
print("new arry elements are:",np.asarray(lis))
        

odd numbers are : [1, 3, 5]
new arry elements are: [2 2 2 4 2 6]


How to reshape an array?

In [6]:
a = np.arange(18).reshape(9,2)
print(a)
print("\n")
b = a.reshape(3,3,2).swapaxes(0,2)
print(b)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


[[[ 0  6 12]
  [ 2  8 14]
  [ 4 10 16]]

 [[ 1  7 13]
  [ 3  9 15]
  [ 5 11 17]]]


Convert a 1D array to a 2D array with 2 rows

In [7]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [8]:
#need to work on it as it is no picking 4 multiples
a = np.array([1,2,3,4,5,6,7,8,9])
lis = [a for a in a.tolist() if a%2 == 1 or n%4 == 0]
lis

[1, 3, 5, 7, 9]

Given array, check if there are any null values and print them out. 

In [9]:
Z = np.random.randint(0,3,(3,10)).astype(float)
Z[:,0] = np.nan
G = np.isnan(Z)
print((G.all(axis=0)).any())

True


How to replace all missing values with 0 in a numpy array

In [10]:
from numpy import *

a = array([[1, 2, 3], [0, 3, NaN]])
where_are_NaNs = isnan(a)
a[where_are_NaNs] = 0
a

array([[1., 2., 3.],
       [0., 3., 0.]])

How to find the count of each unique number in a NumPy array?

In [11]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)
 
uniqueValues, uq_val_count = np.unique(arr,return_counts = True)
 
print('Unique Values : ',uniqueValues)
print('Unique Values count is : ',uq_val_count)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Unique Values count is :  [3 2 2 2 1 1 1 1]


How to convert a numeric to a categorical (text) array?

In [18]:
a=np.array(["a","b"])
print(a.dtype)

#converting character array to numeric array

b=(a.view(np.ubyte)-96).astype('U1')

print(b,b.dtype)


<U1
['1' '1' '1' '1' '2' '1' '1' '1'] <U1


 Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

In [20]:
nl=[]
for x in range(99, 299):
    if (x%5==0)  or (x%7==0):
        nl.append(str(x))
print (','.join(nl))

100,105,110,112,115,119,120,125,126,130,133,135,140,145,147,150,154,155,160,161,165,168,170,175,180,182,185,189,190,195,196,200,203,205,210,215,217,220,224,225,230,231,235,238,240,245,250,252,255,259,260,265,266,270,273,275,280,285,287,290,294,295


Write a program to reverse an array and print

In [25]:
def reverseList(A, start, end): 
    if start >= end: 
        return
    A[start], A[end] = A[end], A[start] 
    reverseList(A, start+1, end-1) 
    return A


In [26]:
A = [1, 2, 3, 4, 5, 6]
reverseList(A, 0, 5) 

[6, 5, 4, 3, 2, 1]